
name: Sid Jayanna
description: ''
url: http://sjayanna.github.io
highlighter: rouge
permalink: /posts/:title/
markdown: kramdown

theme:
  disqus_shortname: sjayanna
  google_analytics: UA-38811488-1

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
